"""Seed rules for the persistent estimating rules registry."""


DEFAULT_HARD_RULES: list[dict] = [
    {
        "rule_id": "rfms.auto_mosaic_min_edge_lte_3",
        "name": "Auto mosaic min edge <= 3",
        "category": "classification",
        "stage": "rfms_parse",
        "status": "active",
        "priority": 100,
        "condition_json": {
            "material_type_in": ["floor_tile", "wall_tile", "backsplash", "tub_shower_surround"],
            "tile_min_edge_inches_lte": 3,
        },
        "action_json": {"set": {"is_mosaic": True}},
        "source": "server/rfms_parser.py",
        "description": "Tile with a minimum parsed edge of 3 inches or less is treated as mosaic.",
        "version": 1,
        "notes": "Catches linear mosaics such as 1x6, 2x12, and 3x16 without catching 4x4 field tile.",
    },
    {
        "rule_id": "rfms.rubber_base_code_fallback",
        "name": "B/WB rubber base fallback",
        "category": "classification",
        "stage": "rfms_parse",
        "status": "active",
        "priority": 90,
        "condition_json": {"item_code_prefix_in": ["B-", "WB-"]},
        "action_json": {"set": {"material_type": "rubber_base", "ai_confidence": 0.5}},
        "source": "server/rfms_parser.py",
        "description": "Unknown material codes beginning with B- or WB- classify as rubber base.",
        "version": 1,
        "notes": "Used only when AI classification leaves a material unknown.",
    },
    {
        "rule_id": "rfms.walkoff_mat_code_fallback",
        "name": "WM carpet tile fallback",
        "category": "classification",
        "stage": "rfms_parse",
        "status": "active",
        "priority": 90,
        "condition_json": {"item_code_prefix_in": ["WM-"]},
        "action_json": {"set": {"material_type": "cpt_tile", "ai_confidence": 0.5}},
        "source": "server/rfms_parser.py",
        "description": "Unknown WM- walk-off mat material codes classify as carpet tile.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "rfms.rubber_sheet_code_fallback",
        "name": "RF rubber sheet fallback",
        "category": "classification",
        "stage": "rfms_parse",
        "status": "active",
        "priority": 90,
        "condition_json": {"item_code_prefix_in": ["RF-"]},
        "action_json": {"set": {"material_type": "rubber_sheet", "ai_confidence": 0.5}},
        "source": "server/rfms_parser.py",
        "description": "Unknown RF- resilient floor material codes classify as rubber sheet.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "rfms.vct_code_fallback",
        "name": "VCT fallback",
        "category": "classification",
        "stage": "rfms_parse",
        "status": "active",
        "priority": 90,
        "condition_json": {"item_code_prefix_in": ["VCT-"]},
        "action_json": {"set": {"material_type": "vct", "ai_confidence": 0.5}},
        "source": "server/rfms_parser.py",
        "description": "Unknown VCT- material codes classify as vinyl composition tile.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "quote_parser.cpt_tile_unit_sy",
        "name": "CPT tile always 3.85/SY",
        "category": "pricing",
        "stage": "quote_parse",
        "status": "active",
        "priority": 80,
        "condition_json": {"material_type": "cpt_tile"},
        "action_json": {"set": {"unit": "SY", "unit_price": 3.85}},
        "source": "server/quote_parser.py",
        "description": "Carpet tile quote parsing normalizes CPT units to square yards and preserves the known 3.85/SY convention.",
        "version": 1,
        "notes": "Registry captures the estimating standard for audit; current parser prompt enforces the SY unit.",
    },
    {
        "rule_id": "labor.tile_dimension_tiers",
        "name": "Ceramic 24x48/48x48 tiers",
        "category": "labor",
        "stage": "labor_calc",
        "status": "active",
        "priority": 85,
        "condition_json": {
            "material_type_in": ["floor_tile", "wall_tile", "backsplash", "tub_shower_surround"],
            "parsed_tile_dimensions_required": True,
        },
        "action_json": {
            "tier_order": [
                {"min_edge_gte": 48, "max_edge_gte": 48, "catalog_keyword": "48x48"},
                {"min_edge_gte": 24, "max_edge_gte": 48, "catalog_keyword": "24x48"},
                {"max_edge_gt": 36, "catalog_keyword": "greater than 36in"},
                {"max_edge_gt": 24, "catalog_keyword": "greater than 24in"},
                {"min_edge_gte": 24, "max_edge_gte": 24, "catalog_keyword": "24x24"},
                {"max_edge_lte": 13, "catalog_keyword": "0-13x0-13"},
                {"default": True, "catalog_keyword": "12x24"},
            ]
        },
        "source": "server/labor_calc.py",
        "description": "Tile labor rows are filtered by parsed dimension tier, with 48x48 and 24x48 matched before broader large-format tiers.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "proposal.tax_excludes_labor",
        "name": "Tax excludes labor",
        "category": "tax",
        "stage": "proposal_generate",
        "status": "active",
        "priority": 100,
        "condition_json": {"tax_rate_gt": 0},
        "action_json": {
            "taxable_components": ["material_cost", "sundry_cost", "freight_cost", "gpm_material_adder"],
            "exclude_components": ["labor_cost", "gpm_labor_adder"],
        },
        "source": "server/proposal_bundler.py",
        "description": "Sales tax applies to material, sundry, freight, and material GPM adder, not labor.",
        "version": 1,
        "notes": "Regenerated proposals recompute deleted-bundle totals using the same tax basis.",
    },
    {
        "rule_id": "proposal.deleted_bundles_stay_deleted",
        "name": "Deleted bundles stay deleted",
        "category": "proposal",
        "stage": "proposal_generate",
        "status": "active",
        "priority": 95,
        "condition_json": {"proposal_data_contains_any": ["deleted_bundles", "deleted_material_codes"]},
        "action_json": {"preserve_deleted_flags_on_regenerate": True},
        "source": "server/main.py",
        "description": "Bundle and material deletion flags from proposal editing survive proposal regeneration.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "labor.sound_mat_thickness_tiers",
        "name": "Sound mat thickness tiers",
        "category": "labor",
        "stage": "labor_calc",
        "status": "active",
        "priority": 80,
        "condition_json": {"material_type": "sound_mat", "description_contains_mm_thickness": True},
        "action_json": {
            "tiers": [
                {"thickness_mm_lt": 3, "catalog_keyword": "less than 3mm"},
                {"thickness_mm_lte": 6, "catalog_keyword": "4mm to 6mm"},
                {"thickness_mm_gt": 6, "catalog_keyword": "more than 7mm"},
            ],
            "default_catalog_keyword": "less than 3mm",
        },
        "source": "server/labor_calc.py",
        "description": "Sound mat labor rows are selected by parsed mm thickness, defaulting to the thinnest tier when unspecified.",
        "version": 1,
        "notes": "",
    },
    {
        "rule_id": "sundry.db_overrides_config",
        "name": "Sundry DB overrides config",
        "category": "sundry",
        "stage": "sundry_calc",
        "status": "active",
        "priority": 100,
        "condition_json": {"company_rates_key": "sundry_rules", "db_value_present": True},
        "action_json": {"load_sundry_rules_from": "company_rates", "fallback": "config.SUNDRY_RULES"},
        "source": "server/sundry_calc.py",
        "description": "Sundry calculator loads DB company-rate rules first and falls back to config defaults only when absent.",
        "version": 1,
        "notes": "Startup seeds company_rates.sundry_rules from config only when missing.",
    },
]
